name: Deploy Supabase Edge Functions

on:
  # Bisa dijalankan manual dari tab Actions
  workflow_dispatch:

  # Otomatis jalan tiap push ke branch main, khusus folder functions
  push:
    branches:
      - main
    paths:
      - 'supabase/functions/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Supabase CLI
        run: npm install -g supabase

      - name: Deploy Supabase Edge Functions
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        run: |
          supabase login --token $SUPABASE_ACCESS_TOKEN
          supabase functions deploy telegram-notify
          supabase functions deploy check-expiring-servers
