name: Deploy Supabase Edge Functions

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'supabase/functions/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Supabase CLI
        run: |
          curl -fsSL https://cli.supabase.com/install.sh | sh -s -- -b /usr/local/bin

      - name: Deploy Supabase Edge Functions
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        run: |
          supabase login --token $SUPABASE_ACCESS_TOKEN
          supabase functions deploy telegram-notify
          supabase functions deploy check-expiring-servers
